### ISSUE TITLE
运行起来了 但是加载不了数据

### ISSUE THREAD

**Issue by lp4298707** [XboxYan/DYTT#10]
不知道是不是电影天堂的域名问题

**Comment by XboxYan** [comment]
如你所见。
很抱歉，那个网站停止运行了，你可以在`api.js`看到请求数据的网站。（好像跟最近打击盗版电影网站有关，如果有其他可用的资源网站可以自行适配一下）

**Comment by XboxYan** [comment]
@lp4298707 目前正在以`https://www.kankanwu.com`为数据来源，有兴趣可以解析一下，现已完成首页。

**Comment by XboxYan** [comment]
@lp4298707 已完成

**Comment by lp4298707** [comment]
> @lp4298707 目前正在以`https://www.kankanwu.com`为数据来源，有兴趣可以解析一下，现已完成首页。

感谢
