### ISSUE TITLE
按照你的方法写了一个context,但是不能按照你的方式消费context

### ISSUE THREAD

**Issue by lp4298707** [XboxYan/DYTT#17]
<Store.Provider
        style={style}
        value={{
          themeColor : themeColor,
          updateColor : this.updateColor.bind(this)
        }}>
        {this.props.children}
      </Store.Provider>
上面是我的提供者

我在消费组件里面这样写
AddTower.contextType = Store;

然后我在消费组件里面用打印this.context 是一个空对象

但是我用react推荐的方式 <Store.Consumer>
        {
          context=>(<View/>)
}
这种方式 就可以访问到我定义的themeColor

**Comment by lp4298707** [comment]
"react": "16.3.1",
我的react版本

**Comment by XboxYan** [comment]
应该是版本原因吧（我的是`16.6`）。

目前有多种订阅方式。

https://zh-hans.reactjs.org/docs/context.html#classcontexttype

![image](https://user-images.githubusercontent.com/19424274/55862046-46172280-5baa-11e9-85fb-7c54e7615f64.png)

**Comment by lp4298707** [comment]
<img width="938" alt="11111" src="https://user-images.githubusercontent.com/38391864/55863969-297ce980-5bae-11e9-935d-41a87576eded.png">
确实如此  那我可以只升级react而不升级react-native 吗?

**Comment by XboxYan** [comment]
你可以试试，但是很多情况下，`react-native`需要与`react`配套使用，不一定成功。

**Comment by lp4298707** [comment]
非常感谢
