### ISSUE TITLE
首页没有数据

### ISSUE THREAD

**Issue by jamninetyfive** [XboxYan/DYTT#7]
首页没有数据，接口挂了么？

**Comment by XboxYan** [comment]
@jamninetyfive  有时候会有点慢，现在可以了，毕竟是网上第三方的资源

**Comment by jamninetyfive** [comment]
> @jamninetyfive 有时候会有点慢，现在可以了，毕竟是网上第三方的资源

iOS 打包出来 还是没有～ 404

**Comment by jamninetyfive** [comment]
![image](https://user-images.githubusercontent.com/5283666/51223835-71f58400-197e-11e9-9231-a017e0d72afb.png)

**Comment by XboxYan** [comment]
@jamninetyfive 不知道是不是样式的问题，`ios`没测试过，你试试`android`的

**Comment by jamninetyfive** [comment]
安卓OK了  视频反转的时候 会出现透明桌面icon的情况。这是react-native-video的问题。

**Comment by XboxYan** [comment]
> 安卓OK了 视频反转的时候 会出现透明桌面icon的情况。这是react-native-video的问题。

这个我也发现了，在翻转的时候能够看到桌面，暂时还没什么办法，其实影响不算大

**Comment by jamninetyfive** [comment]
总体看了下很不错~，效果什么的都很骚，特别是主题方案很新颖，准备借鉴你的 谢谢。
像你推荐几个功能
1.缓存。
2.播放器里面的 倍速啊 各种设置
3.可以增加下面的bottom tab

**Comment by jamninetyfive** [comment]
iphone 就首页是空白，其他页面都可以 目测你你自己写的插件 Scrollviewpager 的问题

**Comment by XboxYan** [comment]
> iphone 就首页是空白，其他页面都可以 目测你你自己写的插件 Scrollviewpager 的问题

有可能吧，这个没有在iphone上测试过
