### ISSUE TITLE
热更新问题

### ISSUE THREAD

**Issue by shitouzhang** [XboxYan/DYTT#8]
感谢作者的项目，我测试热更新点击下载的时候只走了log01 往下就不走了是怎么回事，log2控制台打印不了，，一直停留在正在努力更新中，请等待
       console.log("开始下载更新文件------------01>")
        LayoutAnimation.easeInEaseOut();
        this.setState({status: 1})//download
        const LocalPackage = await this.RemotePackage.download((progress) => {
            console.log("更新文件大小------------02>" + progress)
            this.setState({
                receivedBytes: progress.receivedBytes
            })
            Animated.timing(
                this.width,
                {
                    toValue: parseFloat(progress.receivedBytes / progress.totalBytes).toFixed(2),
                    duration: 150
                }
            ).start();
        })

**Comment by shitou9999** [comment]
问题解决了，我自己的问题
